### PR TITLE
Add name of reviewer to message

### PR DESCRIPTION
**Pull request by tpazitny**
Resolves https://github.com/tpazitny/allthebots/issues/81

### CODE REVIEW

**Comment by conwayje** [comment]
Specs!

**Comment by tpazitny** [comment]
The existing specs don't test for the content of the messages (maybe they should?)

**Comment by tpazitny** [comment]
@conwayje forgot to tag you the first time. The existing specs don't test for the content of the messages, but maybe they should?

**Comment by conwayje** [comment]
Hm.  Looking around at specs...

1.  Let's try to get this PR to have a spec with the username for this particular command
2.  We can open a GH Issue to include names for other specs and handle it when one of us has a few min of downtime
3.  I'm also going to open a PR to move all of the hash definitions to another file, since they're big enough now to warrant it

**Comment by tpazitny** [comment]
@conwayje 

1. I added a test that passes that checks for what's sent via HTTParty - take a look?
2. Will do.
3. The expectation I added in #1 is also now long enough that maybe it should also be moved to a separate file along with the lets? If you agree and if you set up a structure for me to follow, I'm happy to work through the backfilling from #2, but I don't know what sort of format is normally used for a separate file like you described.

**Comment by conwayje** [comment]
1. Spec looks good
2. I already created the issues D:
3. I think you're fine here, don't worry about it

**Pull request merged**
